# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

	config.vm.define "bigchaindb" do |bigchaindb|
		bigchaindb.vm.box = "bento/ubuntu-18.04"
		bigchaindb.vm.hostname = "bigchaindb"
		bigchaindb.vm.network "private_network", ip: "192.168.33.150"
		bigchaindb.vm.synced_folder "./bigchaindb", "/home/vagrant/", type:"virtualbox"
		bigchaindb.vm.provision "shell", path: "script.sh"
		
       
	end
	
end